In [12]:
import numpy as np
A= [[5, 1],
    [1, 5]]

A= np.array(A)
b= [[10],
    [20]]

b= np.array(b)

array([[ 0.20833333, -0.04166667],
       [-0.04166667,  0.20833333]])

In [ ]:
#1
invA= np.linalg.inv(A)
invA

In [18]:
#2
A@b==x
x

array([[1.25],
       [3.75]])

In [14]:
#3
b@A==Y
Y
#無法計算

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [28]:
#4
b=[10,20]
b@A==x
x

array([[-0.00868056],
       [ 0.14756944]])

In [ ]:
#6

In [30]:
#7
x= np.linalg.solve(A, b) 
x

array([1.25, 3.75])

In [31]:
Ai= np.linalg.inv(A)
b= np.linalg.solve(Ai, x) 
b

array([10., 20.])