In [4]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.linalg as la
%matplotlib inline
%precision 4
plt.style.use('ggplot')


# LU Decomposition and Gaussian Elimination

In [5]:

import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print(np.dot(L, U))
print("P:\n",P)
print("L:\n",L)
print("U:\n",U)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[1.     0.     0.    ]
 [0.3333 1.     0.    ]
 [0.6667 0.4    1.    ]]
U:
 [[ 3.  -9.  -3. ]
 [ 0.   5.   4. ]
 [ 0.   0.   6.4]]


In [7]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print("P:\n",P)
print("L:\n",L)
print("U:\n",U)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[1.     0.     0.    ]
 [0.3333 1.     0.    ]
 [0.6667 0.4    1.    ]]
U:
 [[ 3.  -9.  -3. ]
 [ 0.   5.   4. ]
 [ 0.   0.   6.4]]


# Eigendecomposition 

In [8]:
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[ 1.-0.j  2.-0.j  3.+0.j]
 [ 2.-0.j -4.+0.j  6.-0.j]
 [ 3.-0.j -9.+0.j -3.-0.j]]
[ 1.6402+0.j     -3.8201+6.6286j -3.8201-6.6286j]
