In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [115]:
A = np.array([[8,3],[2,5]])
b = np.array([7,15])
x = la.solve(A, b)
np.allclose(A @ x, b)

True

In [116]:
print("A:\n",A)
print("b:\n",b)
print("x:\n",x)

A:
 [[8 3]
 [2 5]]
b:
 [ 7 15]
x:
 [-0.29411765  3.11764706]


In [117]:
import scipy.linalg.lapack as lapack
lu, piv, x, info = lapack.dgesv(A, b)
print("x:\n",x)

x:
 [-0.29411765  3.11764706]


In [118]:
la.solve(A, b)

array([-0.29411765,  3.11764706])

# LU

In [119]:
p, l, u = la.lu(A)
print("p:\n",p)
print("l:\n",l)
print("u:\n",u)

p:
 [[1. 0.]
 [0. 1.]]
l:
 [[1.   0.  ]
 [0.25 1.  ]]
u:
 [[8.   3.  ]
 [0.   4.25]]


# Choleskey

In [120]:
U = la.cholesky(A)
print("U:\n",U)

U:
 [[2.82842712 1.06066017]
 [0.         1.96850197]]


In [121]:
np.allclose(U.T @ U, A)

False

In [122]:
np.allclose(U.T.conj() @ U, A)

False

# QR

In [123]:
Q, R = la.qr(A)
print("Q:\n",Q)

Q:
 [[-0.9701425  -0.24253563]
 [-0.24253563  0.9701425 ]]


In [124]:
np.allclose((la.norm(Q[:,0]), la.norm(Q[:,1])), (1,1))

True

In [125]:
np.allclose(Q@R, A)


True

In [126]:
u, v = la.eig(A)
print("u:\n",u)
print("v:\n",v)

u:
 [9.37228132+0.j 3.62771868+0.j]
v:
 [[ 0.90937671 -0.56576746]
 [ 0.41597356  0.82456484]]


# Inverting A

In [127]:
np.allclose(v @ np.diag(1/u) @ v.T, la.inv(A))

False

# SVD

In [128]:
U, s, V = la.svd(A)
print("U:\n",U)
print("s:\n",s)
print("V:\n",V)

U:
 [[-0.88846694 -0.45894062]
 [-0.45894062  0.88846694]]
s:
 [9.43467835 3.60372646]
V:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


In [129]:
np.allclose((la.norm(V[:,0]), la.norm(V[:,1])), (1,1))

True

In [130]:
np.allclose(U @ np.diag(s) @ V, A)

True