# 3 variables system of linear equations

In [63]:
#n= np.random.randint(最低數值,最高數值) 隨機採樣 
#隨機生成器
np.random.seed(6) 
n=3
A= np.random.randint(-2,2,size=(n,n)) 

np.random.seed(6) 

b= np.random.randint(-2,2,size=(n,1)) 

x= np.linalg.solve(A, b) 
print( "A:\n",A)
print( "b:\n",b)
print( "x:\n",x )


A:
 [[ 0 -1  1]
 [-2  0 -1]
 [ 1  0 -2]]
b:
 [[ 0]
 [-1]
 [ 1]]
x:
 [[ 0.6]
 [-0.2]
 [-0.2]]


##驗算

In [64]:
Ai= np.linalg.inv(A)
b= np.linalg.solve(Ai, x) 
b

array([[-2.22044605e-17],
       [-1.00000000e+00],
       [ 1.00000000e+00]])

# 5 variables system of linear equations

In [65]:
#n= np.random.randint(最低數值,最高數值) 隨機採樣 
#隨機生成器
np.random.seed(8) 
n=5
A= np.random.randint(-2,2,size=(n,n)) 

np.random.seed(8) 

b= np.random.randint(-2,2,size=(n,1)) 

x= np.linalg.solve(A, b) 
print( "A:\n",A)
print( "b:\n",b)
print( "x:\n",x )


A:
 [[ 1 -2 -1 -1 -1]
 [ 0 -2  1 -2  1]
 [-2 -1 -1 -2 -1]
 [ 1  0  1 -2 -1]
 [-1 -1  1 -1  0]]
b:
 [[ 1]
 [-2]
 [-1]
 [-1]
 [-1]]
x:
 [[ 0.25581395]
 [-0.34883721]
 [-0.20930233]
 [ 0.88372093]
 [-0.72093023]]


##驗算

In [66]:
Ai= np.linalg.inv(A)
b= np.linalg.solve(Ai, x) 
b

array([[ 1.],
       [-2.],
       [-1.],
       [-1.],
       [-1.]])

# 10 variables system of linear equations

In [58]:
#n= np.random.randint(最低數值,最高數值) 隨機採樣 
n= np.random.randint(2,10) 
#隨機生成器
np.random.seed(2) 

A= np.random.randint(-5,5,size=(10,10)) 

np.random.seed(2) 

b= np.random.randint(-5,5,size=(10,1)) 

x= np.linalg.solve(A, b) 
print( "A:\n",A)
print( "b:\n",b)
print( "x:\n",x )


A:
 [[ 3  3  1 -3  3  2 -3 -4  0 -1]
 [-1  0  2 -2  1 -1 -2  2  1 -4]
 [-2  0  3 -1  1 -2  4 -3 -5 -1]
 [-3 -1 -4  2  3 -3  4  3  2 -4]
 [ 1  3  0  4  4  4 -2 -5 -5 -3]
 [ 3  3 -3  4  1  0  1  1  1 -2]
 [ 3 -3 -4 -1  3 -4  1  4  0 -4]
 [-3 -1  2  1 -1  0  3 -2 -5 -5]
 [ 0  2  0 -5  3  1  0 -4  2 -1]
 [-2  1 -4 -1 -5  3  0 -1 -3  4]]
b:
 [[ 3]
 [ 3]
 [ 1]
 [-3]
 [ 3]
 [ 2]
 [-3]
 [-4]
 [ 0]
 [-1]]
x:
 [[ 0.28932661]
 [ 1.79022715]
 [ 1.33534126]
 [-0.91532835]
 [ 1.68151746]
 [ 2.4614375 ]
 [ 1.24569794]
 [ 3.18427613]
 [-1.05638238]
 [ 0.81321664]]


##驗證

In [60]:
Ai= np.linalg.inv(A)
b= np.linalg.solve(Ai, x) 
b

array([[ 3.00000000e+00],
       [ 3.00000000e+00],
       [ 1.00000000e+00],
       [-3.00000000e+00],
       [ 3.00000000e+00],
       [ 2.00000000e+00],
       [-3.00000000e+00],
       [-4.00000000e+00],
       [ 7.06032455e-16],
       [-1.00000000e+00]])