# 運算練習

In [13]:
x= 4
y= 5
z= x+y
z

9

In [14]:
def f(x,y):
    z= x+y
    return z

f(1, 2)

3

In [12]:
def add(x,y):
    z= x+y
    return z
def sub(x,y):
    z= x-y
    return z
def mul(x,y):
    z= x*y
    return z
def div(x,y):
    z= x/y
    return z

a= add(1,2)
s= sub(1,2)
m= mul(1,2)
d= div(1,2)
a,s,m,d

(3, -1, 2, 0.5)

In [63]:
class Number:
    
    def __init__(self,x,o):
        self.x= x
        self.o= o
        
    def add(self,y):
        z= self.x + y + self.o
        return z
    
    def sub(self,y):
        z= self.x - y
        return z
    
    def mul(self,y):
        z= self.x * y
        return z
    
    def div(self,y):
        z= self.x / y
        return z

n= Number(100,200)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n.x , a, s, m, d

(100, 301, 99, 100, 100.0)

In [65]:
# 運用繼承的觀念，繼續擴充 物件內涵
# dunder (double under，雙底線) __xxx__

class Number(Number):
        
    def __add__(self,y):
        z= self.add(y)
        return z
    def __sub__(self,y):
        z= self.sub(y)
        return z
    def __mul__(self,y):
        z= self.mul(y)
        return z
    def __truediv__(self,y): # 這個除法的名稱比較特殊
        z= self.div(y)
        return z


n= Number(100,200)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x2c4cc8d2790>, 100, 301, 99, 100, 100.0)

In [42]:
a= n.__add__(2)
s= n.__sub__(2)
m= n.__mul__(2)
d= n.__truediv__(2)
n, n.x, a, s, m, d

(<__main__.Number at 0x2c4cc8d2fd0>, 100, 302, 98, 200, 50.0)

In [68]:
a= n+2
s= n-2
m= n*2
d= n/2
n, n.x, a, s, m, d

(<__main__.Number at 0x2c4cc8d2790>, 100, 302, 98, 200, 50.0)

In [72]:
class Number(Number):
    
    # print our string object
    def __repr__(self):      # 更改 此 物件的 print() 結果。 以字串型態送出去。
        return f'{self.x+self.o}'
    pass
    
    
n= Number(100,200)
n

300

In [73]:
type(n)


__main__.Number

# 向量的加減乘除四則運算

In [74]:
x= [1,2,3]  #list類型 + - / *的符號並不代表數學運算
y= [10,20,30]
x+y

[1, 2, 3, 10, 20, 30]

In [76]:
# 自己定義一個向量物件，使其符合數學上的定義！
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z

v= Vector([1,2,3,4])
v.add([10,20,30,40])

[11, 22, 33, 44]

In [77]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z
    def sub(self,y):    
        z= [xi-yi for xi,yi in zip(self.x, y)]
        return z
    def mul(self,y):    
        z= [xi*yi for xi,yi in zip(self.x, y)]
        return z
    def div(self,y):    
        z= [xi/yi for xi,yi in zip(self.x, y)]
        return z
    
    def __add__(self,y):    
        z= self.add(y)
        return z
    def __sub__(self,y):    
        z= self.sub(y)
        return z
    def __mul__(self,y):    
        z= self.mul(y)
        return z
    def __truediv__(self,y):    
        z= self.div(y)
        return z

In [78]:
v= Vector([1,2,3,4])
a= v + [10,20,30,40]
s= v - [10,20,30,40]
m= v * [10,20,30,40]
d= v / [10,20,30,40]
v.x, a, s, m, d

([1, 2, 3, 4],
 [11, 22, 33, 44],
 [-9, -18, -27, -36],
 [10, 40, 90, 160],
 [0.1, 0.1, 0.1, 0.1])

# Numpy 就是把我們以上作的事情再進一步延伸.... 成為一個偉大的模組 (module)

In [79]:
import numpy as np

In [80]:
v= [1, 2, 3, 4]  #list
v

[1, 2, 3, 4]

In [81]:
v= np.array(v)
v

array([1, 2, 3, 4])

In [82]:
v.shape

(4,)

In [83]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [84]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
A.shape

(2, 4)

In [86]:
T=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [87]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
T.shape

(4, 4)

In [90]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [91]:
T.shape

(2, 2, 4)

In [94]:
T[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
print(v.ndim)
print(A.ndim)
print(T.ndim)

1
2
3


In [98]:
T4d= T.reshape(2,2,2,2)
T4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [99]:
T4d.shape

(2, 2, 2, 2)

In [100]:
v, A, T, T4d

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [101]:
v14= v.reshape(1,4)
v41= v.reshape(4,1)
v14,v41

(array([[1, 2, 3, 4]]),
 array([[1],
        [2],
        [3],
        [4]]))

In [102]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))