In [4]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.linalg as la
%matplotlib inline
%precision 4
plt.style.use('ggplot')


# LU Decomposition and Gaussian Elimination

In [6]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


In [7]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.5    0.1818 1.    ]]
[[4.     1.     2.    ]
 [0.     2.75   3.5   ]
 [0.     0.     1.3636]]


# Cholesky Decomposition

In [8]:
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)

[[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


# Eigendecomposition 

In [5]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+1.0147e-17j  1.+0.0000e+00j]
 [-1.+0.0000e+00j  0.+1.0147e-17j]]
[0.+1.j 0.-1.j]


In [6]:
# If you know the eigenvalues must be real
# because A is a positive definite (e.g. covariance) matrix
# use real_if_close

A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)
print np.real_if_close(u)

SyntaxError: invalid syntax (<ipython-input-6-08d4fbf0ed51>, line 8)

# Stabilty and Condition Number

In [ ]:
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

In [11]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)

ValueError: Input b has to have same number of rows as input a