In [4]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')


# LU

In [11]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
print("A:\n",A)

P, L, U = la.lu(A)
print("np.dot(P.T, A):\n",np.dot(P.T, A))
print("np.dot(L, U):\n",np.dot(L, U))
print("P:\n",P)
print("L:\n",L)
print("U:\n",U)

A:
 [[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]
np.dot(P.T, A):
 [[ 5. 23. 42.]
 [ 1.  3.  5.]
 [ 3. 13. 23.]]
np.dot(L, U):
 [[ 5. 23. 42.]
 [ 1.  3.  5.]
 [ 3. 13. 23.]]
P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[1.  0.  0. ]
 [0.2 1.  0. ]
 [0.6 0.5 1. ]]
U:
 [[ 5.  23.  42. ]
 [ 0.  -1.6 -3.4]
 [ 0.   0.  -0.5]]


# Cholesky Decomposition

In [12]:
L = la.cholesky(A)
print("np.dot(L.T, L):\n",np.dot(L.T, L))
print("L:\n",L)
print("A:\n",A)

np.dot(L.T, L):
 [[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
L:
 [[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
A:
 [[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


# Stabilty and Condition Number

In [13]:
b = np.array([9,39,70])
la.solve(A,b)

array([1., 1., 1.])